schemaVersion: 2.2.0
metadata:
  attributes:
    metadata-name-field: generateName
    metadata-name-original-value: python-fastapi-course
  name: python-fastapi-course
  namespace: sashirestela-dev
attributes:
  che-theia.eclipse.org/sidecar-policy: mergeImage
projects:
  - name: python-fastapi-course
    git:
      remotes:
        origin: https://github.com/sashirestela/python-fastapi-course.git
components:
  - name: universal-developer-image
    container:
      image: quay.io/devfile/universal-developer-image:ubi8-latest
      volumeMounts:
        - name: m2
          path: /home/user/.m2
      mountSources: true
      memoryRequest: 2G
      memoryLimit: 6G
      cpuRequest: 2000m
      cpuLimit: 4000m
  - name: m2
    volume:
      size: 8Gi
commands: []
